### ISSUE TITLE
Where is D:\GTAV-AI\models

### ISSUE THREAD

**Issue by XxPro1445GamerxX** [ikergarcia1996/Self-Driving-Car-in-Video-Games#1]
So I am a fairly new programmer. I am using this as a leap into learning ai, i was wondering where the file D:\GTAV-AI\models was. When you used it in **python run_TEDD1104.py --model_dir D:\GTAV-AI\models --show_current_control** .

**Comment by ikergarcia1996** [comment]
That path is an example. --model_dir parameter expects a path to a pre-trained model directory. You can generate your own data and train the model yourself (train.py and generate_data.py) or you can wait a few days and I will upload pre-trained models that you can download to run the AI.
