### ISSUE TITLE
TypeError: __new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by Nexenek** [ikergarcia1996/Self-Driving-Car-in-Video-Games#14]
Hi! So basicly I am trying to train a new model recorded myself playing with
```
python generate_data.py \
--save_dir "dataset/train" \
--width 1920 \
--height 1080 \
--control_mode keyboard
```
everything went perfect but when I used 

`python train.py --train_new --train_dir dataset/train --val_dir  dataset/dev --output_dir runs/szymon-base --encoder_type transformer --dataloader_num_workers 32 --batch_size 16 --accumulation_steps 1 --max_epochs 10 --cnn_model_name efficientnet_v2_s --num_layers_encoder 1 --embedded_size 384 --learning_rate 5e-5 --mask_prob 0.2 --dropout_cnn_out 0.3 --dropout_encoder 0.1 --dropout_encoder_features 0.3 --control_mode keyboard --val_check_interval 0.25 --precision "bf16" --devices 8 --accelerator tpu --report_to wandb`

and it started downloading something (I don't remember what it was probably something with torch) then crashed. I got this error:
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\Self-Driving-Car-in-Video-Games-5.1.0.XXL\train.py", line 653, in <module>
    train_new_model(
  File "C:\Users\user\Documents\Self-Driving-Car-in-Video-Games-5.1.0.XXL\train.py", line 197, in train_new_model
    model: Tedd1104ModelPL = Tedd1104ModelPL(
  File "C:\Users\user\Documents\Self-Driving-Car-in-Video-Games-5.1.0.XXL\model.py", line 1091, in __init__
    self.train_accuracy = torchmetrics.Accuracy(
TypeError: __new__() missing 1 required positional argument: 'task'
```

So i looked for `__new__()` in files that were showing error 

```
train.py
model.py
```

but I didn't find anything so I decided to create this issue

I would be super thankful if someone could help me to fix this error
Thanks

```
specs:
I5-11400
GTX 1650 528.02
Win 11 22H2 22621.963
```

**Comment by ikergarcia1996** [comment]
The torchmetric API has been updated. After version 0.10.0 torchmetrics Accuray function requires the "task" parameter.  I have updated the code to support torchmetrics >= 0.10.0. 
Run 'git pull' or download the repository again and the error should be solved.

**Comment by Nexenek** [comment]
Thanks a lot!
