### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by djdaniel258** [ikergarcia1996/Self-Driving-Car-in-Video-Games#3]
This error appears when starting the program: "ImportError: cannot import name 'load_model' from 'model' (unknown location)"
Model source has already been indicated in the way shown in the HOW-TO part. In my case, the command I have used is: "python run_TEDD1104.py --model_dir C:\Users\admin\Downloads\GTA V\model --show_current_control" (without the quotation marks).

**Comment by ikergarcia1996** [comment]
Seems like python is not able to locate the model.py file. Check that model.py and  run_TEDD1104.py are in the same directory and that you are running the command from that directory. Does python show any other error message?
