### ISSUE TITLE
prediction always return none

### ISSUE THREAD

**Issue by AlleyBo55** [ikergarcia1996/Self-Driving-Car-in-Video-Games#5]
![image](https://user-images.githubusercontent.com/23420935/109391482-eb2b7780-7949-11eb-8bdd-b342f99ce2d3.png)

im running it with latest release pretrain_model, [pretrain](https://github.com/ikergarcia1996/Self-Driving-Car-in-Video-Games/releases/tag/3.0)
but always return **_key predicted none,_** 
it makes the AI doing nothing
im really stuck of this issue, maybe anyone can help me?

Here is my `pip list`
![image](https://user-images.githubusercontent.com/23420935/109391908-0ac39f80-794c-11eb-9f97-5e15168bd11e.png)

**Comment by ikergarcia1996** [comment]
Gi @adanamanya, sorry for the late response. 
The model seems to be running correctly, but for some reason, it predicts that it should not push any key, this is expected when you open the in-game map or when you don't have any route set in the minimap. It can also happen if python is not able to correctly record the screen, to ensure that this is not happening you can push the "L" key and the images that are currently being used to predict the keys will be displayed so you can test if the program is recoding the game correctly.

**Comment by AlleyBo55** [comment]
it's recording the screen correctly, i can see the dashcam view when pressing "L".
also already set the route on map, is there any other possibilities that causing this?

**Comment by ikergarcia1996** [comment]
What is happening then is that the model thinks that do not push any key is the correct action. I will test again this weekend the model that I released to ensure that it works as expected on my PC and I didn't upload an incorrect model. 

Are you using the first person view with  Settings > First Person Vehicle Hood = On?

**Comment by AlleyBo55** [comment]
This is how it looks when i press L
![image](https://user-images.githubusercontent.com/23420935/110161587-27664880-7e20-11eb-8762-0638f3981f45.png)
i try to print `model_prediction[0]`, it always return 0,  which means `np.asarray([0])` always return` 0`.
what is your numpy version anyway?
also, what is your screen resolution?

**Comment by ikergarcia1996** [comment]
I tested the model/code. It also says for me that the predicted key is always none, however, the model drives as expected. The bug was only affecting the print in the terminal. I have updated the code to fix the bug. Let me know if the change worked for you 

I am using 1600x900 screen resolution for the game (My screen is 2560x1440), the V4 version will allow you to set the game at any resolution you want including full screen, I will release it in a few weeks.

**Comment by AlleyBo55** [comment]
![image](https://user-images.githubusercontent.com/23420935/110209158-7b733a80-7ebd-11eb-99b5-83579683be84.png)
still returning `none`
already setup 1600x900 in game, and 2560x1440 for monitor
is there any possibilities because of my numpy version different than yours? or maybe because my VGA didn't support fp-16? 
i see your model_v3 was trained with fp-16
im running it with command  `python run_TEDD1104.py --model_dir small_V3`
![image](https://user-images.githubusercontent.com/23420935/110209250-02281780-7ebe-11eb-8728-1971ce4b52dd.png)
