### ISSUE TITLE
How to use models with different screen resolutions

### ISSUE THREAD

**Issue by Guanshuyan** [ikergarcia1996/Self-Driving-Car-in-Video-Games#7]
Hello, my screen resolution is 1920x1080. I see that you use 2560x1440 resolution and 1600x900 game resolution. Do you need to adjust the game resolution when running your model on my computer?

**Comment by Guanshuyan** [comment]
by the way I use your V3model

**Comment by ikergarcia1996** [comment]
Hi!
You should run the game in windowed mode (Go to setting or push Alt+Enter) and set the resolution the game settings to 1600x900.
In a few weeks, I will release a new version of the model that uses a new architecture and also allows different resolutions. 

`
How-to:

Set your game in windowed mode  

Set your game to 1600x900 resolution  

Move the game window to the top left corner, there should be a blue line of 1 pixel in the left bezel of your screen and the window top bar should start in the top bezel of your screen.
`

**Comment by Guanshuyan** [comment]
thanks, I do what u say but vehicles seems move stupid，and aimless after moving a distance, 

Can you give me some advice plz

thanks again!

**Comment by ikergarcia1996** [comment]
If you push "L" five small windows will appear. These windows will show the input images for the model, check that the model input is correct.
