### ISSUE TITLE
How to use pre-trained model

### ISSUE THREAD

**Issue by Guanshuyan** [ikergarcia1996/Self-Driving-Car-in-Video-Games#8]
![图片](https://user-images.githubusercontent.com/58554584/143610606-8608a63f-32ce-4d93-b80e-aaf3204b6e98.png)
hi, i use small_V3 model, However,it reports an error and displays unrecognized arguments: -- fp16,

Is it my command input error？

**Comment by ikergarcia1996** [comment]
Remove the --fp16 parameter, sorry it is a mistake of the documentation
