### ISSUE TITLE
Train model

### ISSUE THREAD

**Issue by Guanshuyan** [ikergarcia1996/Self-Driving-Car-in-Video-Games#9]
hi,me again lol
I wonder how long it took you to train the model SmallV3  
ty

**Comment by ikergarcia1996** [comment]
Hi! that model was trained long time ago, I don't remember how long it took. I guess that no more than 1-2 days with the GTX1080 I used. The new V5-base model takes ~8 days with an RTX3090 GPU or 2 days with 2xA100 GPUs.
